### ISSUE TITLE
Error using Datepicker

### ISSUE THREAD

**Issue by geraldmichl** [dharmeshpipariya/md2-datepicker#2]
After installing and using the datepicker i get the following error: 
"Error encountered resolving symbol values statically. Calling function 'Md2DatepickerModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AuthorizedModule in .../authorized.module.ts, resolving symbol AuthorizedModule in .../authorized.module.ts"

**Comment by dharmeshpipariya** [comment]
@geraldmichl please refer [https://github.com/Promact/md2/tree/master/src/lib/datepicker](https://github.com/Promact/md2/tree/master/src/lib/datepicker)
