### ISSUE TITLE
Demo site not work

### ISSUE THREAD

**Issue by xzegga** [dharmeshpipariya/md2-datepicker#3]
Demo site in http://dharmeshpipariya.github.io/md2-datepicker/ not load

**Comment by dukearena** [comment]
Any feedback on that?

**Comment by sunillokhande** [comment]
Hello sir, 
I am using md2-datepicker with angular cli. I am getting the below error while "ng serve" but app works fine with the date picker but "ng build --prod" is not working.

Error : 
ERROR in Error encountered resolving symbol values statically. Calling function 'Md2DatepickerModule', function calls are not supported. Consider replacing the function or lambda with a
reference to an exported function, resolving symbol AppModule in D:/HubnetAmazon/Trunk/HubnetAngular2UI/hubnet-new-ui/src/app/app.module.ts, resolving symbol AppModule in D:/HubnetAmazon
/Trunk/HubnetAngular2UI/hubnet-new-ui/src/app/app.module.ts

My OS : windows 7 64 bit
My Angular Cli version : 1.0.0-rc.0
My Md2DatepickerModule Version : 0.0.1-alpha.1

**Comment by dharmeshpipariya** [comment]
@Muthu2020 please use md2-datepicker -> https://github.com/Promact/md2/tree/master/src/lib/datepicker instead of this, it is also maintained by us.

**Comment by Muthu2020** [comment]
@dharmeshpipariya yeah..but I need only date picker component from your module that why I was using your component.

**Comment by dharmeshpipariya** [comment]
@Muthu2020 you can import md2-datepicker component separately, please refer -> https://github.com/Promact/md2/issues/66

**Comment by Muthu2020** [comment]
@dharmeshpipariya In that way only, I have imported your date picker component.

**Comment by dukearena** [comment]
Demo site still not working.. Can you please reopen it?
Those are the console error:
`GET http://dharmeshpipariya.github.io/md2-datepicker/vendor/core-js/client/core.js 
dharmeshpipariya.github.io/:32 GET http://dharmeshpipariya.github.io/md2-datepicker/vendor/systemjs/dist/system.src.js 
dharmeshpipariya.github.io/:33 GET http://dharmeshpipariya.github.io/md2-datepicker/vendor/zone.js/dist/zone.js 
(index):32 GET http://dharmeshpipariya.github.io/md2-datepicker/vendor/systemjs/dist/system.src.js 
(index):33 GET http://dharmeshpipariya.github.io/md2-datepicker/vendor/zone.js/dist/zone.js 
(index):36 Uncaught ReferenceError: System is not defined
    at (index):36
(anonymous) @ (index):36`
